### ISSUE TITLE
Error when downgrading: "Return value of RectorPrefix202310\Nette\Utils\Reflection::getUseStatements() must be of the type array, null returned"

### ISSUE THREAD

**Issue by bogal** [rectorphp/rector-downgrade-php#196]
Hi, i'm attempting to downgrade a php8.2 app to make it run on a php7.4 environment. Using the following rector.php

```
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src'
    ]);
    $rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon');
    $rectorConfig->importNames();

    $rectorConfig->sets([
        DowngradeLevelSetList::DOWN_TO_PHP_74
    ]);
};
```

... it seems to process most of the files ok, but then chokes on several others with the following error message (output from --debug flag):

 

> [ERROR] Could not process                                                                                             
>          "/var/www/my-app/src/Service/REST/SomeService.php" file, due to:
>          "System error: "Return value of RectorPrefix202310\Nette\Utils\Reflection::getUseStatements() must be of the  
>          type array, null returned" 
> 
>          Stack trace:                                                                                                  
>          #0 vendor/rector/rector/vendor/nette/utils/src/Utils/Reflection.php(209):                                     
>          RectorPrefix202310\Nette\Utils\Reflection::getUseStatements()                                                 
>          #1 vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(208):                         
>          RectorPrefix202310\Nette\Utils\Reflection::expandClassName()                                                  
>          #2 vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(179):                         
>          Rector\CodingStyle\ClassNameImport\ShortNameResolver->fqnizeShortNames()                                      
>          #3 vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(144):                         
>          Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveFromStmtsDocBlocks()                             
>          #4 vendor/rector/rector/rules/CodingStyle/ClassNameImport/ShortNameResolver.php(85):                          
>          Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveForStmts()                                       
>          #5                                                                                                            
>          vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/FullyQualifiedNameClassNameImp
>          ortSkipVoter.php(35): Rector\CodingStyle\ClassNameImport\ShortNameResolver->resolveFromFile()                 
>          #6 vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipper.php(39):                     
>          Rector\CodingStyle\ClassNameImport\ClassNameImportSkipVoter\FullyQualifiedNameClassNameImportSkipVoter->shoul 
>          dSkip()                                                                                                       
>          #7 vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(79):                                          
>          Rector\CodingStyle\ClassNameImport\ClassNameImportSkipper->shouldSkipNameForFullyQualifiedObjectType()        
>          #8 vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(47):                                          
>          Rector\CodingStyle\Node\NameImporter->importNameAndCollectNewUseStatement()                                   
>          #9 vendor/rector/rector/packages/PostRector/Rector/NameImportingPostRector.php(137):                          
>          Rector\CodingStyle\Node\NameImporter->importName()                                                            
>          #10 vendor/rector/rector/packages/PostRector/Rector/NameImportingPostRector.php(97):                          
>          Rector\PostRector\Rector\NameImportingPostRector->processNodeName()                                           
>          #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                        
>          Rector\PostRector\Rector\NameImportingPostRector->enterNode()                                                 
>          #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                        
>          PhpParser\NodeTraverser->traverseArray()                                                                      
>          #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                        
>          PhpParser\NodeTraverser->traverseNode()                                                                       
>          #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                        
>          PhpParser\NodeTraverser->traverseArray()                                                                      
>          #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                        
>          PhpParser\NodeTraverser->traverseNode()                                                                       
>          #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                         
>          PhpParser\NodeTraverser->traverseArray()                                                                      
>          #17 vendor/rector/rector/packages/PostRector/Application/PostFileProcessor.php(59):                           
>          PhpParser\NodeTraverser->traverse()                                                                           
>          #18 vendor/rector/rector/src/Application/FileProcessor.php(120):                                              
>          Rector\PostRector\Application\PostFileProcessor->traverse()                                                   
>          #19 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):                                   
>          Rector\Core\Application\FileProcessor->processFile()                                                          
>          #20 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):                                   
>          Rector\Core\Application\ApplicationFileProcessor->processFile()                                               
>          #21 vendor/rector/rector/src/Console/Command/WorkerCommand.php(132):                                          
>          Rector\Core\Application\ApplicationFileProcessor->processFiles()                                              
>          #22 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                           
>          Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}()                            
>          #23 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                       
>          RectorPrefix202310\Evenement\EventEmitter->emit()                                                             
>          #24 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                           
>          RectorPrefix202310\Clue\React\NDJson\Decoder->handleData()                                                    
>          #25 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                
>          RectorPrefix202310\Evenement\EventEmitter->emit()                                                             
>          #26 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                           
>          RectorPrefix202310\React\Stream\Util::RectorPrefix202310\React\Stream\{closure}()                             
>          #27 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                               
>          RectorPrefix202310\Evenement\EventEmitter->emit()                                                             
>          #28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                               
>          RectorPrefix202310\React\Stream\DuplexResourceStream->handleData()                                            
>          #29 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                               
>          RectorPrefix202310\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                  
>          #30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(90):                                           
>          RectorPrefix202310\React\EventLoop\StreamSelectLoop->run()                                                    
>          #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                     
>          Rector\Core\Console\Command\WorkerCommand->execute()                                                          
>          #32 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                         
>          RectorPrefix202310\Symfony\Component\Console\Command\Command->run()                                           
>          #33 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                         
>          RectorPrefix202310\Symfony\Component\Console\Application->doRunCommand()                                      
>          #34 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                              
>          RectorPrefix202310\Symfony\Component\Console\Application->doRun()                                             
>          #35 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                         
>          Rector\Core\Console\ConsoleApplication->doRun()                                                               
>          #36 vendor/rector/rector/bin/rector.php(130): RectorPrefix202310\Symfony\Component\Console\Application->run() 
>          #37 vendor/rector/rector/bin/rector(4): require_once('/var/www/my-ap...')                                    
>          #38 vendor/bin/rector(115): include('/var/www/my-ap...')                                                     
>          #39 {main}". On line: 235

  

What does it mean?

**Comment by samsonasik** [comment]
Downgrade process should not use `$rectorConfig->importNames();` as it is complex process, could you try disable it?

Also, could you create reproducible code and config at https://getrector.com/demo ? Thank you.

**Comment by bogal** [comment]
Hi, i removed importNames and it worked fine. Thanks!
