### ISSUE TITLE
[DowngradeProcOpenArrayCommandArgRector] Command line is not escaped

### ISSUE THREAD

**Issue by garas** [rectorphp/rector-downgrade-php#198]
When code `proc_open($array)` is downgraded, it just simply concatenates array with space.

Main reason of using array is that `proc_open` takes care of any necessary argument escaping.

But if any argument contains space, it becomes two separate arguments. It can even become security issue.

I got this issue when trying to run `vendor/bin/rector process "/path/my project/src"`, XdebugHandler will restart as `vendor/bin/rector process /path/my project/src` and fail because wrong path. 

https://github.com/composer/xdebug-handler/blob/3.0.3/src/XdebugHandler.php#L298
is refactored to
https://github.com/rectorphp/rector/blob/0.18.5/vendor/composer/xdebug-handler/src/XdebugHandler.php#L240

One of possibility to fix is to `array_map` with `escapeshellarg`.

**Comment by samsonasik** [comment]
@garas could you create a failing fixture at https://github.com/rectorphp/rector-downgrade-php/tree/main/rules-tests/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector/Fixture  ? thank you.

**Comment by garas** [comment]
`fixture.php.inc` should refactor
```diff
-$process = proc_open($command, $descriptorspec, $pipes, null, null, ['suppress_errors' => true]);
+$process = proc_open(is_array($command) ? implode(' ', array_map('escapeshellarg', $command)) : $command, $descriptorspec, $pipes, null, null, ['suppress_errors' => true]);
```

`non_variable.php.inc` should refactor
```diff
-$process = proc_open(['rm', '-r', 'my dir'], $descriptorspec, $pipes, null, null, ['suppress_errors' => true]);
+$process = proc_open(is_array(['rm', '-r', 'my dir']) ? implode(' ', array_map('escapeshellarg', ['rm', '-r', 'my dir'])) : ['rm', '-r', 'my dir'], $descriptorspec, $pipes, null, null, ['suppress_errors' => true]);
```
