### ISSUE TITLE
ArrowFunctionToAnonymousFunctionRector with DowngradeArrayIsListRector wouldn't work

### ISSUE THREAD

**Issue by rafark** [rectorphp/rector-downgrade-php#204]
I'm previewing a project that should be downgraded to PHP 7.2 using -dry-run and I'm getting this preview when using array_is_list() inside a short closure:

`    ---------- begin diff ----------
@@ @@
         );
     }

-    public function convertToObject(array $items) : mixed
+    /**
+     * @return mixed
+     */
+    public function convertToObject(array $items)
     {
+        $arrayIsListFunction = function (array $array) : bool {
+            if (function_exists('array_is_list')) {
+                return array_is_list($array);
+            }
+            if ($array === []) {
+                return true;
+            }
+            $current_key = 0;
+            foreach ($array as $key => $noop) {
+                if ($key !== $current_key) {
+                    return false;
+                }
+                ++$current_key;
+            }
+            return true;
+        };
         return array_map(
-            fn(mixed $item) => is_array($item) && !array_is_list($item)? (object) $this->convertToObject($item) : ($item),
+            function ($item) {
+                return is_array($item) && !$arrayIsListFunction($item)? (object) $this->convertToObject($item) : ($item);
+            },
             $items
         );
     }
    ----------- end diff -----------

Applied rules:
 * ArrowFunctionToAnonymousFunctionRector (https://www.php.net/manual/en/functions.arrow.php)
 * DowngradeMixedTypeDeclarationRector
 * DowngradeArrayIsListRector (https://wiki.php.net/rfc/is_list)`

The main problem is that DowngradeArrayIsListRector creates a **local** variable with the polyfill function but then it is being used inside the converted function from ArrowFunctionToAnonymousFunctionRector and regular closures don't have access to the outer scope, so this code will never run:

`
return array_map(
-            fn(mixed $item) => is_array($item) && !array_is_list($item)? (object) $this->convertToObject($item) : ($item),
+            function ($item) {
+                return is_array($item) && !$arrayIsListFunction($item)? (object) $this->convertToObject($item) : ($item);
+            },
             $items
         );
` 

DowngradeArrayIsListRector needs to explicty require the outer variable in the closure with a `use($arrayIsListFunction)`, so the function above should be:

`return array_map(
-            fn(mixed $item) => is_array($item) && !array_is_list($item)? (object) $this->convertToObject($item) : ($item),
+            function ($item) use ($arrayIsListFunction)  {
+                return is_array($item) && !$arrayIsListFunction($item)? (object) $this->convertToObject($item) : ($item);
+            },
             $items
         );
` `

**Comment by rafark** [comment]
I'm thinking DowngradeArrayIsListRector should run before ArrowFunctionToAnonymousFunctionRector so that the later can be aware of the local variable created by DowngradeArrayIsListRector

**Comment by samsonasik** [comment]
Could you reproduce at https://getrector.com/demo ? Thank you.

**Comment by rafark** [comment]
Sure, give me a couple of minutes

**Comment by rafark** [comment]
> Could you reproduce at https://getrector.com/demo ? Thank you.

Here it is: https://getrector.com/demo/8cc96a71-3b45-411c-b74a-fa78b4580bce

notice that `$arrayIsListFunction($item)` will never get called because the function generated by ArrowFunctionToAnonymousFunctionRector doesn't import $arrayIsListFunction (by using `use ($arrayIsListFunction)`)

**Comment by samsonasik** [comment]
The display of `Applied rules` is sorted alphabetically iirc, so it unrelated with that, the issue is when arrow function changed to closure, the node still detected as arrow function on other rule.
