### ISSUE TITLE
match with UnhandledMatchError

### ISSUE THREAD

**Issue by AlexP11223** [rectorphp/rector-downgrade-php#227]
Looks like code like this

```
        try {
            match ($age) {
                1, 2 => foo(),
                3, 4 => bar(),
            };
        } catch (\UnhandledMatchError $e) {
            var_dump($e);
        }
```

is currently transpiled into

```
        try {
            switch ($age) {
                case 1:
                case 2:
                    foo();
                    break;
                case 3:
                case 4:
                    bar();
                    break;
            }
        } catch (\UnhandledMatchError $e) {
            var_dump($e);
        }
```

which is not the same behavior, unhandled matches are just ignored.

I think an easy fix could be just to somehow add a polyfil for `UnhandledMatchError` and add a `default` in `switch` throwing it when there is no `default` in `match`.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by AlexP11223** [comment]
https://getrector.com/demo/2e60980d-8947-41d7-b840-11299c17d288

**Comment by TomasVotruba** [comment]
Thanks! Could you create a test fixture with proposed code using a "Create test" button?

**Comment by AlexP11223** [comment]
hm, it would not be easy to express in such form because I am not sure about this part of my proposal:

> somehow add a polyfil for UnhandledMatchError

Was something like this ever done in Rector?

**Comment by TomasVotruba** [comment]
Polyfill would require the project to install it in requires.
Rector is only dev dependency.

I think more generic exception should be used instead.

**Comment by AlexP11223** [comment]
I mean maybe a way can be found to declare a polyfil when the generated code needs it. Not sure if there is any suitable way to dynamically insert a class, maybe via `eval` or [this solution](https://stackoverflow.com/a/52861290/964478), if not then maybe a solution can be generating a file for polyfils at the end of processing and asking the developer to include it somewhere (composer or just `if file_exists` + `require` on project boot). This solution probably can be useful for other features, e.g. `Stringable`.

Or an alternative can be to throw `UnhandledMatchError` if it exists (provided by some other polyfil dep), and throw more generic if not. But throwing another exception is weird because it changes the PHP 8 behavior and makes it more difficult to trust Rector.

**Comment by TomasVotruba** [comment]
We'll need working prototype to verify these scenarios.

**Comment by samsonasik** [comment]
`UnhandledMatchError` should not be used in practice imo, as not existed data should be handled early before match, or use default fallback instead.

**Comment by samsonasik** [comment]
I am closing it as `UnhandledMatchError` is not practical, update the code to handle early, or use default fallback inside the match to throw https://3v4l.org/ABLDi

Thank you for understanding.
