### ISSUE TITLE
Some question about this project, and why remove aoubt `downgrade php70` 

### ISSUE THREAD

**Issue by xuanyanwow** [rectorphp/rector-downgrade-php#228]
Question 1: this project's content is one part of `rectorphp/rector` project at before. split it make every project simple and clear. It's right?

Question 2: about https://github.com/rectorphp/rector/issues/6079   why some content about downgrade to 7.0  5.6  missed in this downgrade rules project?

**Comment by TomasVotruba** [comment]
Hi, thanks for the ping 


1. Yes, these sets are shipped in rector/rector 

2. There were two reasons to keep maintenance saint and rules reliable. The main demand for upgrade in tools was PHP 7.2 and 7.1. Second is rules targeting lower PHP were not always realiable and required manual work.



What's your use case to downgrade?
