### ISSUE TITLE
bug [DowngradeUnionTypeDeclarationRector] Downgrade to php 7.4

### ISSUE THREAD

**Issue by dingedi** [rectorphp/rector-downgrade-php#26]
```php
class MyClass {

public array|false $property = array();

}
```
is downgraded to 
```php
class MyClass {

   /**
     * @var mixed[]|true
     */
    public $property = array();

}
```

my rector config
```php
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\DowngradeLevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
    ]);

    $rectorConfig->sets([
        DowngradeLevelSetList::DOWN_TO_PHP_74,
    ]);
};
```

**Comment by samsonasik** [comment]
The issue seems on `PropertyTypeDecorator` which `false` in union docblock changed to `true`

**Comment by samsonasik** [comment]
@dingedi that seems can be handled by set php version in the config after sets:

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Set\ValueObject\DowngradeLevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        DowngradeLevelSetList::DOWN_TO_PHP_74,
    ]);
    $rectorConfig->phpVersion(PhpVersion::PHP_80);
};
```

see https://getrector.org/demo/cf2d0618-100f-4e77-9851-39a3488632cf

**Comment by dingedi** [comment]
> @dingedi that seems can be handled by set php version in the config after sets:
> 
> ```php
> <?php
> 
> use Rector\Config\RectorConfig;
> use Rector\Core\ValueObject\PhpVersion;
> use Rector\Set\ValueObject\DowngradeLevelSetList;
> 
> return static function (RectorConfig $rectorConfig): void {
>     $rectorConfig->sets([
>         DowngradeLevelSetList::DOWN_TO_PHP_74,
>     ]);
>     $rectorConfig->phpVersion(PhpVersion::PHP_80);
> };
> ```
> 
> see https://getrector.org/demo/cf2d0618-100f-4e77-9851-39a3488632cf

Thanks
