### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by szepeviktor** [rectorphp/rector-downgrade-php#8]
Spotted that.

**Comment by TomasVotruba** [comment]
Copy-paste PR? :slightly_smiling_face:

**Comment by szepeviktor** [comment]
Sent in 2 seconds :)

**Comment by szepeviktor** [comment]
@TomasVotruba The Cleaning Lady could warn you about the license file ...
https://web.archive.org/web/20200831185120/https://tomasvotruba.com/cleaning-lady-checklist/

**Comment by TomasVotruba** [comment]
@szepeviktor Thank you 🚀 

She's retired now, waiting for A.I. brain to replace us all 😴😅
